### ISSUE TITLE
Is legitimate ap's entropy computed with 6 params?

### ISSUE THREAD

**Issue by DongBeiDaMao** [jayluxferro/IoT-IDS#8]
Sorry , I find another thing that I don't understand. When compute the entropy of legitimate ap , how much params were used? Is it 14 , the same number as when you compute entropy of rogue ap? 

The paper shows that only 6 params were used:
    1.Basic Service Set Identifier (BSSID)
    2.Channel
    3.Frequency
    4.Protocol
    5.Cipher
    6.Supported bit rate(s)
I think there must be something I misunderstood. Could you please explain these questions for me? Thank you.

**Comment by jayluxferro** [comment]
Hello @DongBeiDaMao , initially I did a detailed analysis of the wireless frames to determine which characteristics were relevant. With that I got 14 characteristics. Later on I realised not all the characteristics are really really relevant in the classification of the legitimate AP. So I just selected the 6 params.

**Comment by DongBeiDaMao** [comment]
So the entropy of rogue AP is also computed with 6 characteristics  , is that right?

**Comment by jayluxferro** [comment]
Yes it is.

**Comment by DongBeiDaMao** [comment]
Then why compute the entropy? If the result is obtained by comparing whether the params are exactly the same , an accumulator is enough. Like below:

count = 0
if ap_info['group_cipher'] == data['group_cipher']:                
    count += 1
if ap_info['protocol'] == data['protocol']:                
    count += 1
    .
    .
    .
    .
if ap_info['mode'] == data['mode']:
    count += 1

if count != 6:
    False
else:
    True

**Comment by jayluxferro** [comment]
Using an accumulator is right. I chose the entropy because with that you can give some degree of relevance to all the 14 characteristics; assuming I chose to use all of them. I could have used an accumulator in my case too. The entropy gives a fundamental basic theory for identifying the relevance of the characteristics. Now I realised later on that I could have used all those 14 characteristics, done some parameter tuning with conventional machine learning models and even use ML to classify. Which makes the whole classification computation a little lighter.

**Comment by DongBeiDaMao** [comment]
Thank you, I understand. Entropy can provide basic theory for detection methods based on machine learning , like decision tree.

**Comment by jayluxferro** [comment]
yeah. You're welcome. Thanks a lot too.
